! r2 - AS 65002 (transit)  (SOLUTION)
frr version 8.4
frr defaults traditional
hostname r2
log stdout
no ipv6 forwarding
!
interface lo
 ip address 2.2.2.2/32
!
interface eth1
 ip address 10.0.12.2/24
!
interface eth2
 ip address 10.0.23.2/24
!
router bgp 65002
 no bgp ebgp-requires-policy
 neighbor 10.0.12.1 remote-as 65001
 neighbor 10.0.23.3 remote-as 65003
 network 2.2.2.2/32
!
line vty
!
