! r1 - AS 65001  (SOLUTION)
frr version 8.4
frr defaults traditional
hostname r1
log stdout
no ipv6 forwarding
!
interface lo
 ip address 1.1.1.1/32
!
interface eth1
 ip address 10.0.12.1/24
!
router bgp 65001
 neighbor 10.0.12.2 remote-as 65002
!
line vty
!
