! r2 - AS 65002  (SOLUTION)
frr version 9.1
frr defaults traditional
hostname r2
log stdout
no ipv6 forwarding
!
interface lo
 ip address 2.2.2.2/32
!
interface eth1
 ip address 10.0.12.2/24
!
router bgp 65002
 neighbor 10.0.12.1 remote-as 65001
!
line vty
!
