! r1 - AS 65001  (SOLUTION)
frr version 8.4
frr defaults traditional
hostname r1
log stdout
no ipv6 forwarding
!
interface lo
 ip address 1.1.1.1/32
!
interface eth1
 ip address 10.0.12.1/24
!
interface eth2
 ip address 10.0.34.1/24
!
router bgp 65001
 no bgp ebgp-requires-policy
 neighbor 10.0.12.2 remote-as 65002
 neighbor 10.0.34.2 remote-as 65002
 network 1.1.1.1/32
 neighbor 10.0.12.2 route-map MED-LOW out
 neighbor 10.0.34.2 route-map MED-HIGH out
!
route-map MED-LOW permit 10
 set metric 50
!
route-map MED-HIGH permit 10
 set metric 200
!
line vty
!
